-- Create new user with required permissions to use OSAK
-- Replace <OSAK_USER_PASSWORD> with your password

CREATE USER OSAK_USER IDENTIFIED BY <OSAK_USER_PASSWORD>;
GRANT DBA TO OSAK_USER;
GRANT CONNECT TO OSAK_USER;
GRANT OSAK_ADMIN_ROLE TO OSAK_USER;