DECLARE
    NUM_ROWS_LOADED INTEGER := 0;
BEGIN
    SYS.DBMS_KAFKA.EXECUTE_LOAD_APP ( 'OSSCLUSTER', 'OSSLOADAPP', 'MY_LOADED_DATA', NUM_ROWS_LOADED);
END;
/
-- the message is stored as json in VARCHAR data type
SELECT
    JSON_VALUE(VALUE, '$.key'),
    JSON_VALUE(VALUE, '$.ts'),
    KAFKA_OFFSET
FROM
    MY_LOADED_DATA
ORDER BY
    KAFKA_OFFSET DESC FETCH NEXT 10 ROWS ONLY;